akka {
  loglevel = "INFO"
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
  license-key = "3CecWl2jfui8lwcoAI0pXu8Qq78PNOHSH8LOPTXKTbWP4ToghtBH6XO4eEojJEJWMg8gtMyQWYiaj0BKayDNHNqP9VB1lNypgER415LWHe8b3aIGhF2dcmirS5qsvP3k8KYHIs9aWeYJ5G7JyFT2MEjeFND3E3mbbaV5Z3FcFTt1"

  actor {
    provider = "local"
    serialization-bindings {
      "java.io.Serializable" = java
    }
  }

  kafka.consumer {
    kafka-clients {
      bootstrap.servers = ${?KAFKA_BOOTSTRAP_SERVERS}
      enable.auto.commit = true
      auto.commit.interval.ms = 5000
      session.timeout.ms = 30000
      request.timeout.ms = 40000
    }
    wait-close-partition = 500ms
    position-timeout = 5s
    close-timeout = 20s
    use-dispatcher = "akka.kafka.default-dispatcher"
  }

  kafka.producer {
    kafka-clients {
      bootstrap.servers = ${?KAFKA_BOOTSTRAP_SERVERS}
    }
  }
}

kafka {
  # Connection
  bootstrap-servers = ${KAFKA_BOOTSTRAP_SERVERS}

  # Topics
  topics {
    user-requests = "user-requests"
    user-lifecycle = "user-lifecycle-events"
    node-requests = "node-management-requests"
    node-lifecycle = "node-lifecycle-events"

    # Raw measurements coming from Node-RED
    measurements-raw = "measurements-raw"

    # Validated measurements published by MeasurementService
    measurement-events = "measurement-events"

    # Periodic usage and cost summaries published by BillingService
    usage-records = "usage-records"

    # Ping pong test topic
    ping-pong = "ping_pong"
  }

  # AccountService Consumer
  account-consumer {
    group-id = "account-service-group"
    auto-offset-reset = "latest"
  }

  # DistrictNodeManager Consumer
  node-consumer {
    group-id = "district-node-manager-group"
    auto-offset-reset = "latest"
  }

  # MeasurementService Consumer
  measurement-consumer {
    group-id = "measurement-service-group"
    auto-offset-reset = "latest"
  }

  # BillingService Consumer
  billing-consumer {
    group-id = "billing-service-group"
    auto-offset-reset = "latest"
  }

  # User Lifecycle Consumer
  user-lifecycle-consumer {
    group-id = "user-service-lifecycle-group-"${?INSTANCE_ID}
    auto-offset-reset = "earliest"
  }

  # DistrictNodeManager Node Lifecycle Consumer
  node-lifecycle-consumer {
    group-id = "node-lifecycle-group-"${?INSTANCE_ID}
    auto-offset-reset = "earliest"
  }

  # BillingService Lifecycle Consumer
    billing-usage-consumer {
      group-id = "billing-service-usage-group-"${?INSTANCE_ID}
      auto-offset-reset = "earliest"
    }
  # BillingService Usage Consumer
  billing-usage-consumer {
    group-id = "billing-usage-group"
    auto-offset-reset = "earliest"
  }

  # PingPongService Consumer
  ping-pong-consumer {
    group-id = "ping-pong-service-group"
    auto-offset-reset = "latest"
  }
}
